# Generated by Django 6.0.6 on 2026-07-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0006_recommendation_book_recommended_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
